#ifndef __INTERRUPT_SERVICE_H__
#define __INTERRUPT_SERVICE_H__

//Reserved Exceptions
void ISRDividError();
void ISRDebug();
void ISRNMI();
void ISRBreakPoint();
void ISROverflow();
void ISRBoundRangeExceeded();
void ISRInvalidOpCode();
void ISRDeviceNotAvailable();
void ISRDoubleFault();
void ISRCoProcessorSegmentOverrun();
void ISRInvalidTSS();
void ISRSegmentNotPresent();
void ISRStackSegmentFault();
void ISRGeneralProtection();
void ISRPageFault();
void ISR15();
void ISRFloatingPointError();
void ISRAlignmentCheck();
void ISRMachineCheck();
void ISRSIMDError();
void ISRDefaultException();
//PIC Interrupt
void ISRTimer();
void ISRPS2Keyboard();
void ISRSlavePIC();
void ISRSerialPort2();
void ISRSerialPort1();
void ISRParallel2();
void ISRFloppy();
void ISRParallel1();
void ISRRTC();
void ISRReserved();
void ISRNotUsed1();
void ISRNotUsed2();
void ISRPS2Mouse();
void ISRCoprocessor();
void ISRHDD1();
void ISRHDD2();
void ISRDefaultInterrupt();
#endif /* __INTERRUPT_SERVICE_H__ */